import Feed from '@/components/shared/feed'
import Post from '@/components/shared/post'
import React from 'react'
//fecthing json posts generated by chatgpt
interface User {
  id: number;
  name: string;
  username: string;
  email: string;
}

interface Post {
  userId: number;
  id: number;
  title: string;
  body: string;
}

export interface PostWithUser extends Post {
  username: string;
  profilePicture: string;
  email:string
}

async function getPostsWithUserDetails(): Promise<PostWithUser[]> {
  try {
    const [postsResponse, usersResponse] = await Promise.all([
      fetch('https://jsonplaceholder.typicode.com/posts'),
      fetch('https://jsonplaceholder.typicode.com/users')
    ]);

    const posts: Post[] = await postsResponse.json();
    const users: User[] = await usersResponse.json();

    const postsWithUsers: PostWithUser[] = posts.map(post => {
      const user = users.find(user => user.id === post.userId);
      return {
        ...post,
        username: user?.username || 'Unknown',
        email: user?.email||'email.com',
        profilePicture: `https://robohash.org/${user?.username}.png?size=50x50`
      };
    });

    return postsWithUsers;
  } catch (error) {
    console.error('Error fetching data:', error);
    return [];
  }
}


const page =async () => {
  const posts =await getPostsWithUserDetails()
    const hrs = new Date().getHours()
    const  wish =hrs<= 16 ? (hrs>=12 ? 'Good Afternoon': 'Good Morning') : 'Good Evening'
  return (
    <div className='w-full h-full flex flex-col items-center justify-center '>
     <div className='flex flex-col w-full items-start'>
     <h2 className='font-bold text-2xl'>{wish} Musheer</h2>
     <p className='text-sm text-muted-foreground'>check out todays latest posts</p>
     </div>
     <Feed posts={posts}/>
    </div>
  )
}

export default page