import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import {Toaster} from 'sonner'
const font= DM_Sans({
  subsets: ['latin','latin-ext']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased p-2 flex flex-col min-h-screen h-full w-full`}
      >
        <Toaster/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
